setup:
  commands:
  - apt-get install -y xorg-dev libglfw3-dev
  - ./UpdateDependencies.bash
  - mkdir Build
  - cd Build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make

tests:
  commands:
  - ./bin/TestConfig
  - ./bin/TestUnits