
# C++
language: cpp

# Run on both Ubuntu 14.04 and OS X 10.9.5
os:
  - linux
  - osx
sudo: required
dist: trusty

# Run both Debug and Releas
env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

install:
  # Necessary packages
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ContinuousIntegration && InstallGLFW.bash
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd ..
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install glfw3; fi

  # Pull github dependencies
  - ./Dependencies/Clone.bash

script:
  - mkdir Build && cd Build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
  - make
  - ./TestConfig/TestConfig
  - ./TestUnits/TestUnits
