version: 0.4.4.b{build}
image: Visual Studio 2017

install:
  - cd Dependencies
  - Clone.bat
  - cd ..
  - git clone https://github.com/Microsoft/vcpkg
  - cd vcpkg
  - powershell -exec bypass scripts\bootstrap.ps1
  - vcpkg install glfw3:x64-windows
  - vcpkg integrate install
  - cd ..

build:
  project: ionEngine.sln
  verbosity: minimal

test_script:
  - x64\Debug\TestUnits.exe
